# Generated by Django 5.0 on 2023-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='categories',
        ),
        migrations.AddField(
            model_name='company',
            name='logo_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_country_flag',
            field=models.CharField(max_length=255),
        ),
    ]
