# Generated by Django 5.0 on 2023-12-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_categories_company_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_image',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
