# Generated by Django 5.0 on 2023-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_image',
            field=models.CharField(max_length=255),
        ),
    ]
